# Configuration pour l'optimiseur de maillage interne SEO

# Configuration OpenAI
openai:
  api_key: "YOUR_API_KEY_HERE"  # Remplacez par votre clé API
  model: "text-embedding-3-small"  # Options: text-embedding-3-small, text-embedding-3-large, text-embedding-ada-002
  dimensions: null  # null pour dimensions par défaut, ou 256/512/768/1024/1536

# Configuration du crawl
crawl:
  user_agent: "Mozilla/5.0 (compatible; SEO Internal Linking Bot/1.0; +http://votre-site.com/bot)"
  respect_robots_txt: true
  delay_between_requests: 1.0  # Secondes entre chaque requête
  max_workers: 3  # Nombre de threads parallèles (1-5)
  timeout: 15  # Timeout par requête en secondes
  max_retries: 3  # Nombre de tentatives en cas d'échec
  
  # Patterns d'URL à exclure
  excluded_patterns:
    - "/wp-admin/"
    - "/admin/"
    - "/login"
    - "/logout"
    - "/cart/"
    - "/checkout/"
    - "/my-account/"
    - "/tag/"
    - "/author/"
    - "/feed/"
    - ".xml"
    - "/page/"  # Pagination
    - "?print="  # Versions print
    - "?share="  # Liens de partage
  
  # Extensions de fichiers à ignorer
  excluded_extensions:
    - ".pdf"
    - ".jpg"
    - ".jpeg"
    - ".png"
    - ".gif"
    - ".webp"
    - ".mp3"
    - ".mp4"
    - ".avi"
    - ".zip"
    - ".rar"
    - ".exe"
    - ".dmg"
    - ".iso"
    - ".doc"
    - ".docx"
    - ".xls"
    - ".xlsx"
    - ".ppt"
    - ".pptx"

# Configuration de l'analyse
analysis:
  links_per_page: 5  # Nombre de liens à recommander par page
  min_similarity_score: 0.7  # Score minimum pour recommander un lien (0.0-1.0)
  batch_mode_threshold: 500  # Nombre de pages à partir duquel activer le mode batch
  
  # Pondération pour le calcul de pertinence (optionnel)
  weights:
    title: 2.0
    h1: 1.5
    meta_description: 1.0
    content: 1.0

# Configuration des rapports
output:
  formats:
    - html  # Rapport interactif HTML
    - csv   # Export CSV pour Excel
    - json  # Export JSON pour développeurs
  
  html_options:
    include_preview: true  # Inclure un aperçu du contenu
    highlight_opportunities: true  # Mettre en avant les meilleures opportunités
    show_orphan_pages: true  # Identifier les pages sans liens internes

# Limites de sécurité
limits:
  max_pages_to_crawl: 1000  # Limite absolue pour éviter les crawls infinis
  max_content_length: 30000  # Caractères max par page (évite les pages trop lourdes)
  max_embedding_batch: 100  # Nombre max d'embeddings à créer d'affilée

# Configuration avancée
advanced:
  use_cache: true  # Utiliser le cache pour éviter de re-crawler
  cache_expiry_days: 7  # Durée de validité du cache
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  save_raw_data: false  # Sauvegarder les données brutes extraites